# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(676, 383)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView_img = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_img.setGeometry(QtCore.QRect(20, 49, 260, 260))
        self.graphicsView_img.setObjectName("graphicsView_img")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(310, 100, 71, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_restore = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_restore.setFont(font)
        self.pushButton_restore.setObjectName("pushButton_restore")
        self.verticalLayout.addWidget(self.pushButton_restore)
        self.pushButton_gen = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_gen.setFont(font)
        self.pushButton_gen.setObjectName("pushButton_gen")
        self.verticalLayout.addWidget(self.pushButton_gen)
        self.graphicsView_result = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_result.setGeometry(QtCore.QRect(400, 49, 260, 260))
        self.graphicsView_result.setObjectName("graphicsView_result")
        self.pushButton_Compare = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Compare.setGeometry(QtCore.QRect(600, 10, 61, 31))
        self.pushButton_Compare.setObjectName("pushButton_Compare")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(321, 60, 51, 16))
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(310, 80, 69, 21))
        self.spinBox.setObjectName("spinBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 676, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        self.menuMask = QtWidgets.QMenu(self.menubar)
        self.menuMask.setObjectName("menuMask")
        self.menuCorner_Mask = QtWidgets.QMenu(self.menuMask)
        self.menuCorner_Mask.setObjectName("menuCorner_Mask")
        self.menuHalf_Mask = QtWidgets.QMenu(self.menuMask)
        self.menuHalf_Mask.setObjectName("menuHalf_Mask")
        self.menuRandom_Mask = QtWidgets.QMenu(self.menubar)
        self.menuRandom_Mask.setObjectName("menuRandom_Mask")
        self.menuFree_Mask = QtWidgets.QMenu(self.menubar)
        self.menuFree_Mask.setObjectName("menuFree_Mask")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionOpen.setFont(font)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionSave.setFont(font)
        self.actionSave.setObjectName("actionSave")
        self.action50_Mask = QtWidgets.QAction(MainWindow)
        self.action50_Mask.setObjectName("action50_Mask")
        self.actionRandom_Block = QtWidgets.QAction(MainWindow)
        self.actionRandom_Block.setObjectName("actionRandom_Block")
        self.actionCentral_Mask = QtWidgets.QAction(MainWindow)
        self.actionCentral_Mask.setObjectName("actionCentral_Mask")
        self.actionRandom_Walk = QtWidgets.QAction(MainWindow)
        self.actionRandom_Walk.setObjectName("actionRandom_Walk")
        self.actionTop_Left_Corner = QtWidgets.QAction(MainWindow)
        self.actionTop_Left_Corner.setObjectName("actionTop_Left_Corner")
        self.actionBottom_Left_Corner = QtWidgets.QAction(MainWindow)
        self.actionBottom_Left_Corner.setObjectName("actionBottom_Left_Corner")
        self.actionTop_Right_Corner = QtWidgets.QAction(MainWindow)
        self.actionTop_Right_Corner.setObjectName("actionTop_Right_Corner")
        self.actionBottom_Right_Corner = QtWidgets.QAction(MainWindow)
        self.actionBottom_Right_Corner.setObjectName("actionBottom_Right_Corner")
        self.actionLeft = QtWidgets.QAction(MainWindow)
        self.actionLeft.setObjectName("actionLeft")
        self.actionRight = QtWidgets.QAction(MainWindow)
        self.actionRight.setObjectName("actionRight")
        self.actionTop = QtWidgets.QAction(MainWindow)
        self.actionTop.setObjectName("actionTop")
        self.actionBottom = QtWidgets.QAction(MainWindow)
        self.actionBottom.setObjectName("actionBottom")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionDraw = QtWidgets.QAction(MainWindow)
        self.actionDraw.setObjectName("actionDraw")
        self.actionThickness = QtWidgets.QAction(MainWindow)
        self.actionThickness.setObjectName("actionThickness")
        self.actionwearMask = QtWidgets.QAction(MainWindow)
        self.actionwearMask.setObjectName("actionwearMask")
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionSave)
        self.menu.addAction(self.actionExit)
        self.menuCorner_Mask.addAction(self.actionTop_Left_Corner)
        self.menuCorner_Mask.addAction(self.actionBottom_Left_Corner)
        self.menuCorner_Mask.addAction(self.actionTop_Right_Corner)
        self.menuCorner_Mask.addAction(self.actionBottom_Right_Corner)
        self.menuHalf_Mask.addAction(self.actionLeft)
        self.menuHalf_Mask.addAction(self.actionRight)
        self.menuHalf_Mask.addAction(self.actionTop)
        self.menuHalf_Mask.addAction(self.actionBottom)
        self.menuMask.addAction(self.actionCentral_Mask)
        self.menuMask.addAction(self.menuCorner_Mask.menuAction())
        self.menuMask.addAction(self.menuHalf_Mask.menuAction())
        self.menuMask.addAction(self.actionwearMask)
        self.menuRandom_Mask.addAction(self.actionRandom_Block)
        self.menuRandom_Mask.addAction(self.actionRandom_Walk)
        self.menuFree_Mask.addAction(self.actionDraw)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuMask.menuAction())
        self.menubar.addAction(self.menuRandom_Mask.menuAction())
        self.menubar.addAction(self.menuFree_Mask.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_restore.setText(_translate("MainWindow", "还原"))
        self.pushButton_gen.setText(_translate("MainWindow", "生成"))
        self.pushButton_Compare.setText(_translate("MainWindow", "比对"))
        self.label.setText(_translate("MainWindow", "画笔大小："))
        self.menu.setTitle(_translate("MainWindow", "图片"))
        self.menuMask.setTitle(_translate("MainWindow", "标准掩码"))
        self.menuCorner_Mask.setTitle(_translate("MainWindow", "四分掩码"))
        self.menuHalf_Mask.setTitle(_translate("MainWindow", "二分掩码"))
        self.menuRandom_Mask.setTitle(_translate("MainWindow", "随机掩码"))
        self.menuFree_Mask.setTitle(_translate("MainWindow", "自由掩码"))
        self.actionOpen.setText(_translate("MainWindow", "打开 "))
        self.actionSave.setText(_translate("MainWindow", "保存"))
        self.action50_Mask.setText(_translate("MainWindow", "Half Mask"))
        self.actionRandom_Block.setText(_translate("MainWindow", "随机方块"))
        self.actionCentral_Mask.setText(_translate("MainWindow", "中心掩码"))
        self.actionRandom_Walk.setText(_translate("MainWindow", "随机墨迹"))
        self.actionTop_Left_Corner.setText(_translate("MainWindow", "左上角"))
        self.actionBottom_Left_Corner.setText(_translate("MainWindow", "左下角"))
        self.actionTop_Right_Corner.setText(_translate("MainWindow", "右上角"))
        self.actionBottom_Right_Corner.setText(_translate("MainWindow", "右下角"))
        self.actionLeft.setText(_translate("MainWindow", "左部"))
        self.actionRight.setText(_translate("MainWindow", "右部"))
        self.actionTop.setText(_translate("MainWindow", "顶部"))
        self.actionBottom.setText(_translate("MainWindow", "底部"))
        self.actionExit.setText(_translate("MainWindow", "退出"))
        self.actionDraw.setText(_translate("MainWindow", "脸部涂鸦"))
        self.actionThickness.setText(_translate("MainWindow", "画笔大小"))
        self.actionwearMask.setText(_translate("MainWindow", "口罩掩码"))
